force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation_line_item__c/Reservation_line_item__c.object-meta.xml
<CustomObject>
    <label>Reservation Line Item</label>
    <nameField>
        <label>Reservation Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation_line_item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

.history/force-app/main/default/classes/ReservationController_20220301075550.cls
public class ReservationController {


    public static void createReservationItem(List<Reservation__c> reservations){


        for(Reservation__c r: reservations){


            Reservation_line_item__c rlineItem = new Reservation_line_item__c{

                Name = r.Name + ' - ' + r.Number_of_Days__c + ' stay. ' + r.Owner,
                Product2 = '01t7Q000000VIqvQAG',
                hotel



            }

        }



    }

}