force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/TTM_ACV__c.field-meta.xml
<CustomField>
    <fullName>TTM_ACV__c</fullName>
    <label>Trailing 12 Month ACV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check-In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Reservation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Amount__c</fullName>
    <label>Reservation Amount</label>
    <summarizedField>Reservation_line_item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Reservation_line_item__c.Reservation__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

.history/force-app/main/default/classes/updateHotelMetricsBatchable_20220907102748.cls
public with sharing class updateHotelMetricsBatchable implements Database.Batchable<sObject> {

    public String query = 'SELECT Id,TTM_ACV__c from Hotel__c';

    public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

    public void execute(Database.BatchableContext BC, List<Hotel__c> scope){

        list<AggregateResult> ReservationAmount = [SELECT sum(Reservation_Amount__c) amt, Room__r.Hotel__c FROM Reservation__c
                                       where check_in_date__c = LAST_N_MONTHS:12 GROUP BY Room__r.Hotel__c];

        map<Id,Decimal> aggACV = new map<Id,Decimal>();

        for(AggregateResult agg: ReservationAmount){
        aggACV.put((Id)agg.get('Hotel__c'), (Decimal)agg.get('amt'));
        }


        
        for(list<hotel__c> hlist: [SELECT Id,TTM_ACV__c from Hotel__c]){
                list<hotel__c> hotelsUpdate = new list<hotel__c>();
                for(hotel__c h:hlist){
                    if(aggACV.containsKey(h.id)){
                        h.TTM_ACV__c = aggACV.get(h.id);
                    }
                    else {
                        h.TTM_ACV__c = 0;
                    }
                    hotelsUpdate.add(h);
                }
                update hotelsUpdate;
                    }

    }

   public void finish(Database.BatchableContext BC){


   }

}