force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Air_Condition__c.field-meta.xml
<CustomField>
    <fullName>Air_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air Condition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Jacuzzi__c.field-meta.xml
<CustomField>
    <fullName>Jacuzzi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jacuzzi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Mini_Bar__c.field-meta.xml
<CustomField>
    <fullName>Mini_Bar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mini Bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/tv__c.field-meta.xml
<CustomField>
    <fullName>tv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>King</fullName>
            </value>
            <value>
                <fullName>President Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/roomGenerator_20220225023806.cls
public class roomGenerator {

    public static void generateRooms(list<Hotel__c> hotelList){

        //Prepare data
        list<Hotel__c> queryList = [Select Id,Name from Hotel__c where Id IN: hotelList];
        //Create list to upload
        list<Room__c> uploadList = new list <Room__c>();
        //Available rooms
        list<String> typeList = new list<String>{'single','double','king','President Suite'};


    for(Hotel__c h:queryList){
        for(Integer i=0;i<typeList.size();i++){

        Room__c ht = new Room__c(
        Hotel__c = h.Id,
        Name = TypeList[i] + ' Room ' + h.Name,
        Room_Number__c = 0,
        Type__c = TypeList[i],
        Mini_Bar__c = true,
        Available__c = true,
        Air_Condition__c = true,
        tv__c = true,
        jacuzzi__c = TypeList[i] == 'President Suite' ? true : false);
      uploadList.add(ht);
        }
    }
       insert uploadList;
    }


    public static void updateRoomsNumbers{}

}