force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>DR Congo</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Iran</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Tanzania</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check-In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_Date__c</fullName>
    <label>Check-out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Max_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Guests__c</fullName>
    <label>Max Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/photo_url__c.field-meta.xml
<CustomField>
    <fullName>photo_url__c</fullName>
    <description>Photo stored in static resources url</description>
    <label>Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>King</fullName>
            </value>
            <value>
                <fullName>President Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/roomController_20220613074548.cls
public class roomController {

    public class DATESRANGE{

    @AuraEnabled
    public String dateName {get;set;}
     @AuraEnabled
    public String dateValue {get;set;}

    }

    public class FILTERSAPEX {
        @AuraEnabled
        public list<String> rooms {get;set;}
        @AuraEnabled
        public String city {get;set;}
        @AuraEnabled
        public String hotel {get;set;}
        @AuraEnabled
        public String country {get;set;}
        //@AuraEnabled
        //public list<DATESRANGE> reservationDates {get;set;}

        @AuraEnabled
        public String startDate {get;set;}
        @AuraEnabled
        public String endDate {get;set;}

        @AuraEnabled
        public String numberOfGuests {get;set;}
        @AuraEnabled
        public Boolean available {get;set;}

}


    @AuraEnabled (cacheable = true)
    public static list<Room__c> roomDisplayList(FILTERSAPEX filters){

        FILTERSAPEX filterData = filters;
        String countryName;
        String cityName;
        String hotelName;
        Date hotelStartDate;
        Date hotelEndDate;

        list<String> logicList = new list<String>();
        String logicDatesList = '';
        String logic = '';
        String logicDate = '';
        String logicDate1 = '';
        String logicDate2 = '';
        String testString = '';

        String queryLogic;


        if(filterData != null){

            if(filterData.country != null){

                countryName = filterData.country;

                logicList.add('Hotel__r.Country__c =: countryName');

        }
            if(filterData.city != null){

                cityName = filterData.city;

                logicList.add('Hotel__r.City__c =: cityName');

            }
            if(filterData.hotel != null){

                hotelName = filterData.hotel;



            }

            testString = filterData.startDate + filterData.endDate;

            if(testString != ''){

                hotelStartDate = date.newInstance(Integer.valueOf(filterData.startDate.substring(0,4)),Integer.valueOf(filterData.startDate.substring(5,7)),Integer.valueOf(filterData.startDate.substring(8,10)));

                hotelEndDate = date.newInstance(Integer.valueOf(filterData.endDate.substring(0,4)),Integer.valueOf(filterData.endDate.substring(5,7)),Integer.valueOf(filterData.endDate.substring(8,10)));

                logicDatesList = '(Check_In_Date__c <=: hotelStartDate AND Check_out_Date__c >=: hotelEndDate) OR (Check_In_Date__c >=: hotelStartDate AND Check_out_Date__c <=: hotelEndDate)';

            }

            if(logicDatesList != ''){
            logicDate1 = ' AND Id NOT IN (Select Room__c FROM Reservation__c WHERE ' + logicDatesList + ' )';
            logicDate2 = ' Id NOT IN (Select Room__c FROM Reservation__c WHERE ' + logicDatesList + ' )';
            }

            else{

                logicDate1 = '';
                logicDate2 = '';
            }

                if(logicList.size()>0){

                    logic = ' WHERE ' + String.join(logicList, ' AND ') + logicDate1;
                }
                else{

                    logic = ' WHERE ' + logicDate2;
                }

        }


        queryLogic = 'Select Id,Hotel__r.Name,Hotel__r.City__c,Hotel__r.Country__c,Name, (SELECT Id, Name, Check_In_Date__c, Check_out_Date__c, Room__c FROM Reservations__r), Available__c,Type__c,Room_Number__c,photo_url__c,Max_Number_of_Guests__c FROM Room__c' + logic;

        list<Room__c> roomList = Database.query(queryLogic);

        return roomList;
    }


    public static list<Room__c> roomList(list<Hotel__c> hlist){

        list<Room__c> roomList = [Select Id,Name,Available__c,Type__c,Room_Number__c from Room__c WHERE Hotel__c IN: hlist];

        return roomList;
    }

    public static list<Room__c> availableRooms(list<Hotel__c> hlist){

        list<Room__c> availableRooms = [Select Id,Name,Available__c,Type__c,Room_Number__c from Room__c WHERE Hotel__c IN: hlist AND Available__c = true];

        return availableRooms;
    }

    public static list<Room__c> occupiedRooms(list<Hotel__c> hlist){

        list<Room__c> occupiedRooms = [Select Id,Name,Available__c,Type__c,Room_Number__c from Room__c WHERE Hotel__c IN: hlist AND occupied__c = true];
        return occupiedRooms;
    }

    public static list<Room__c> endReservation(){

        list<Room__c> endReservation = [Select Id,Name,Available__c,Type__c,Room_Number__c from Room__c WHERE occupied__c = true AND ID IN (SELECT Room__c from Reservation__c WHERE Check_out_Date__c = TODAY)];

        return endReservation;

    }

}