force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Rooms_Available__c.field-meta.xml
<CustomField>
    <fullName>Rooms_Available__c</fullName>
    <label>Rooms Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rooms_out_of_service__c.field-meta.xml
<CustomField>
    <fullName>Rooms_out_of_service__c</fullName>
    <label>Rooms out of service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Total_Rented_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Total_Rented_Rooms__c</fullName>
    <label>Total Rented Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/total_rooms__c.field-meta.xml
<CustomField>
    <fullName>total_rooms__c</fullName>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox - if room required service</description>
    <label>service</label>
    <type>Checkbox</type>
</CustomField>

.history/force-app/main/default/classes/roomTriggerAfterUpdateTest_20220228110914.cls
@IsTest
public class roomTriggerAfterUpdateTest {

    static testMethod void testUnit(){

//Create hotel to test
    Hotel__c h = new hotel__c (
        Name = 'tst',
        City__c = 'Nibylandia',
        total_rooms__c = 5,
        Rooms_Available__c = 5);

        insert h;

    Hotel__c h2 = new hotel__c (
        Name = 'tst',
        City__c = 'Nibylandia2',
        total_rooms__c = 5,
        Rooms_Available__c = 5);

        insert h2;


    list<Room__c> rUpdate = new list<Room__c>();

    // create 160 rooms test
    for(integer i = 0; i<160;i++){
        Room__c r = new Room__c(
            Name = 'test',
            Room_Number__c = i+1,
            Hotel__c = h.Id,
            Available__c = TRUE
            );

        rUpdate.add(r);
        }
        Room__c r2 = new Room__c(
            Name = 'test',
            Room_Number__c = 161,
            Hotel__c = h.Id,
            service__c = true
            );

        rUpdate.add(r2);

        Room__c r3 = new Room__c(
            Name = 'test',
            Room_Number__c = 162,
            Hotel__c = h.Id,
            occupied__c = true
            );

        rUpdate.add(r3);

        Room__c r4 = new Room__c(
            Name = 'test',
            Room_Number__c = 163,
            Hotel__c = h2.Id,
            occupied__c = true,
            service__c = false,
            Available__c = false
            );

        rUpdate.add(r4);


// Performe Test
test.startTest();

    insert rUpdate;

    list<Room__c> UpdateList = [Select Id,Name,Room_Number__c,Hotel__c,service__c,occupied__c,Available__c FROM Room__c];
    list<Room__c> updateListFinal = new list<Room__c>();

    for(Room__c r : UpdateList){

        if(r.Room_Number__c <= 50){

            r.service__c = true;
            r.Available__c = false;
            updateListFinal.add(r);
        }

        else if (r.Room_Number__c > 50 && r.Room_Number__c <= 80){

            r.Available__c = true;
            r.occupied__c = false;
            updateListFinal.add(r);
        }
        else if (r.Room_Number__c == 161){

            r.Available__c = true;
            r.occupied__c = false;
            r.service__c = false;
            updateListFinal.add(r);
        }
        else if (r.Room_Number__c == 162){

            r.Available__c = true;
            r.occupied__c = false;
            r.service__c = false;
            updateListFinal.add(r);
        }
        else {

            r.Available__c = false;
            r.occupied__c = true;
            updateListFinal.add(r);
        }
    }
    update updateListFinal;

Test.stopTest();

Hotel__c hotelData = [Select Id,Rooms_out_of_service__c,Rooms_Available__c,Total_Rented_Rooms__c from Hotel__c];
system.debug(hotelData);

system.assertEquals(33,hotelData.Rooms_Available__c);
system.assertEquals(50,hotelData.Rooms_out_of_service__c);

}

    }