force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/total_rooms__c.field-meta.xml
<CustomField>
    <fullName>total_rooms__c</fullName>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

.history/force-app/main/default/classes/roomTriggerHandler_20220226090117.cls
public with sharing class roomTriggerHandler {


    public roomTriggerHandler() {

        for(Room__c r :Trigger.new){
            hotelList.add(r.Hotel__c);
            }
    
            list<Hotel__c> hList = [Select Id,total_rooms__c from Hotel__c WHERE Id IN: hotelList];
    
            Map<Id, Hotel__c> hotelMap = new Map<Id, Hotel__c>(hList);
    
            for(Room__c rc : Trigger.new){
    
                if(rc.Room_Number__c <= hotelMap.get(rc.Hotel__c).total_rooms__c){
    
                    rc.addError('Room with this number already exisit! Please use number > ' + hotelMap.get(rc.Hotel__c).total_rooms__c); // prevent create
                }
    
            }
    }
}