force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Rooms_Available__c.field-meta.xml
<CustomField>
    <fullName>Rooms_Available__c</fullName>
    <label>Rooms Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

.history/force-app/main/default/classes/roomTriggerTest_20220226083952.cls
@isTest

public class roomTriggerTest {

static testMethod void testUnit(){

//Create hotel to test
Hotel__c h = new hotel__c (
    Name = 'tst',
    City__c = 'Nibylandia',
    Rooms_Available__c = 5);
insert h;
list<Room__c> rUpdate = new list<Room__c>();

// create 160 rooms test
for(integer i = 0; i<160;i++){
Room__c r = new Room__c(
Name = 'test',
Room_Number__c = 1,
Hotel__c = h.Id
);
rUpdate.add(r);
}

test.startTest();
insert rUpdate;
Test.stopTest();

list<Room__c> roomsInserted = [Select Id from Room__c];

system.assertEquals(0, roomsInserted);

}


}