force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Clone_of__c.field-meta.xml
<CustomField>
    <fullName>Clone_of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clone_of</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

.history/force-app/main/default/classes/SOLID/cloneHotel_20221124035001.cls
public with sharing class cloneHotel implements CloneInterface {

    /*
        This class implement interface and must include the same methods as Interface class!!!
    */

    public Opportunity cloneRecord(Id recordId){
        system.debug('This is clone Oppty logic running');

        Hotel__c oldRecord = [Select Id,Name,City__c,OwnerId FROM Hotel__c where Id=: recordId];

        Hotel__c opp = new Hotel__c();
        opp.Name =oldRecord.Name + ' Cloned';
        opp.AccountId = oldRecord.AccountId;
        opp.OwnerId = oldRecord.OwnerId;
        opp.Clone_of__c = oldRecord.Id;
        opp.StageName = oldRecord.StageName;
        opp.CloseDate = oldRecord.CloseDate;

        insert opp;
        return opp;

    }

    public void cloneRelatedRecords(Id recordId){
        system.debug('This is clone related Oppty records logic running');

    }


}