force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>DR Congo</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Iran</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Tanzania</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rating_Stars__c.field-meta.xml
<CustomField>
    <fullName>Rating_Stars__c</fullName>
    <description>Image representation of Rating__c field</description>
    <formula>IMAGE( 
CASE( Rating__c, 
&quot;1&quot;, &quot;/img/samples/stars_100.gif&quot;,
&quot;2&quot;, &quot;/img/samples/stars_200.gif&quot;,
&quot;3&quot;, &quot;/img/samples/stars_300.gif&quot;, 
&quot;4&quot;, &quot;/img/samples/stars_400.gif&quot;, 
&quot;5&quot;, &quot;/img/samples/stars_500.gif&quot;, 
&quot;/img/samples/stars_000.gif&quot;), 
&quot;rating&quot;)</formula>
    <inlineHelpText>Custom formula based on Rating__c</inlineHelpText>
    <label>Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rooms_Available__c.field-meta.xml
<CustomField>
    <fullName>Rooms_Available__c</fullName>
    <label>Rooms Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rooms_out_of_service__c.field-meta.xml
<CustomField>
    <fullName>Rooms_out_of_service__c</fullName>
    <label>Rooms out of service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Total_Rented_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Total_Rented_Rooms__c</fullName>
    <label>Total Rented Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/total_rooms__c.field-meta.xml
<CustomField>
    <fullName>total_rooms__c</fullName>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/TTM_ACV__c.field-meta.xml
<CustomField>
    <fullName>TTM_ACV__c</fullName>
    <label>Trailing 12 Month ACV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

.history/force-app/main/default/classes/hotelController_20220902045933.cls
public class hotelController {


    public static void roomNumber() {
    list<Hotel__c> hotels = [Select Id,Name,Rooms_Available__c FROM Hotel__c];
    Map<Id, Hotel__c> hotelMap = new Map<Id, Hotel__c>(hotels);
    }

    @AuraEnabled (cacheable = true)
    public static list<AggregateResult> countryList(){
        return  [SELECT Country__c FROM Hotel__c WHERE Country__c <> NULL GROUP BY Country__c];
    }

       @AuraEnabled (cacheable = true)
    public static list<AggregateResult> cityList(String countryName){

        String Country = countryName;

        if(String.isEmpty(Country)){

            return  [SELECT City__c FROM Hotel__c WHERE City__c <> NULL GROUP BY City__c];

        } else {

            return  [SELECT City__c FROM Hotel__c WHERE City__c <> NULL AND Country__c =: Country GROUP BY City__c];
        }


    }

    @AuraEnabled (cacheable = true)
    public static list<AggregateResult> hotelList(String countryName,String cityName){

        String CountryFilter = countryName;
        String CityFilter = cityName;

        list<String> formulaKeys = new list<String>{};
        String formula = '';

       if(!String.isEmpty(CountryFilter)){
        formulaKeys.add('Country__c =: CountryFilter');
       }

      if(!String.isEmpty(CityFilter)){
        formulaKeys.add('City__c =: CityFilter');
       }

      if(formulaKeys.size()>0){
        formula = ' WHERE ' + String.join(formulaKeys, ' AND ');
      }

        String query = 'SELECT Id,Name FROM Hotel__c' + formula + ' LIMIT 10';

        return Database.query(query);

}
    @AuraEnabled (cacheable = true)
    public static list<Hotel__c> hotelListDropdown(){

        return [SELECT Id,Name,TTM_ACV__c,total_rooms__c,Total_Rented_Rooms__c,Rooms_out_of_service__c,Rooms_Available__c,Rating__c,City__c,Country__c from Hotel__c];

}

  @AuraEnabled (cacheable = true)
    public static Hotel__c returnHotelData(String Hid){

        return [SELECT Id,Name,TTM_ACV__c,total_rooms__c,Rating_Stars__c,Total_Rented_Rooms__c,Rooms_out_of_service__c,Rooms_Available__c,Rating__c,City__c,Country__c from Hotel__c WHERE Id =: Hid];

    }
}