force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/total_rooms__c.field-meta.xml
<CustomField>
    <fullName>total_rooms__c</fullName>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Air_Condition__c.field-meta.xml
<CustomField>
    <fullName>Air_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air Condition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Jacuzzi__c.field-meta.xml
<CustomField>
    <fullName>Jacuzzi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jacuzzi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Max_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Guests__c</fullName>
    <label>Max Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Mini_Bar__c.field-meta.xml
<CustomField>
    <fullName>Mini_Bar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mini Bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/photo_url__c.field-meta.xml
<CustomField>
    <fullName>photo_url__c</fullName>
    <description>Photo stored in static resources url</description>
    <label>Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/tv__c.field-meta.xml
<CustomField>
    <fullName>tv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>King</fullName>
            </value>
            <value>
                <fullName>President Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/roomMaintenance_20230401163708.cls
public class roomMaintenance {

    public String imageUrl = Consts.ROOM_IMAGE.IMAGE_SOURCE.ImageUrl;

    public class roomType{
        String name;
        String url;}

    public static void generateRooms(list<Hotel__c> hotelList){

        //Prepare data
        list<Hotel__c> queryList = [Select Id,Name from Hotel__c where Id IN: hotelList];
        //Create list to upload
        list<Room__c> uploadList = new list <Room__c>();
        //Available rooms

       list<String> roomTypes = new list<String>{'Single','Double','King','President Suite'};

       list<roomType> roomList = new list<roomType>();

       for(Integer i=1;i<=roomTypes.size();i++){
        roomType r = new roomType();
        r.name = roomTypes[i-1];
        r.url = imageUrl + '/photo' + Integer.valueof((1+ Math.random() * 10)) + '.jpg';
        roomList.add(r);

       }


    for(Hotel__c h:queryList){
        for(Integer i=1;i<=roomList.size();i++){

        Room__c ht = new Room__c(
        Hotel__c = h.Id,
        Name = roomList[i-1].name + ' Room ' + h.Name,
        Type__c = roomList[i-1].name,
        Mini_Bar__c = true,
        Available__c = true,
        Air_Condition__c = true,
        tv__c = true,
        Room_Number__c=i,
        jacuzzi__c = roomList[i-1].name == 'President Suite' ? true : false,
        photo_url__c = roomList[i-1].url,
        Max_Number_of_Guests__c = roomList[i-1].name == 'President Suite' ? 5 : roomList[i-1].name == 'King' ? 4 : roomList[i-1].name == 'Double' ? 2 : 1
        );
      uploadList.add(ht);
        }
    }
       insert uploadList;
    }

    public static void updateHotelRoomsCount(List<Hotel__c> hotelList) {

        AggregateResult[] aggRooms = [SELECT Hotel__c, count(Id) ct FROM Room__c WHERE Hotel__c IN:hotelList group by Hotel__c];

        map<String,Integer> hotelwithRoomCount = new map<String,Integer>();
        list<Hotel__c> updateListHotels = new list<Hotel__c>();

        for(AggregateResult agg: aggRooms){
        hotelwithRoomCount.put(String.valueOf(agg.get('Hotel__c')), Integer.valueOf(agg.get('ct')));
        }
        list<Hotel__c> hotelsList = [Select ID,(Select Id from Rooms__r) from Hotel__c WHERE id IN: hotelwithRoomCount.keySet()];

        for(Hotel__c h : hotelsList){

            h.total_rooms__c = hotelwithRoomCount.get(h.Id);
            updateListHotels.add(h);
        }
        update updateListHotels;
    }

    public static void updateRoomNumbers(List<Hotel__c> hotelList) {
        AggregateResult[] aggRooms = [SELECT Hotel__c, count(Id) ct FROM Room__c WHERE Hotel__c IN:hotelList group by Hotel__c];

        map<String,Integer> hotelwithRoomCount = new map<String,Integer>();
        list<Room__c> updateListRoom = new list<Room__c>();

        for(AggregateResult agg: aggRooms){
        hotelwithRoomCount.put(String.valueOf(agg.get('Hotel__c')), Integer.valueOf(agg.get('ct')));
        }

        list<Hotel__c> hotelsList = [Select ID,(Select Id from Rooms__r) from Hotel__c WHERE id IN: hotelwithRoomCount.keySet()];

        for(Hotel__c h : hotelsList){

            Integer roomNum = 1;
            for(Room__c r :h.Rooms__r){

            r.Room_Number__c = roomNum;
            updateListRoom.add(r);
            roomNum++;

            }
        }
        update updateListRoom;

    }

}