force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/total_rooms__c.field-meta.xml
<CustomField>
    <fullName>total_rooms__c</fullName>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox - if room required service</description>
    <label>service</label>
    <type>Checkbox</type>
</CustomField>

.history/force-app/main/default/classes/roomTriggerHandler_20220228053545.cls
public class roomTriggerHandler {


    public static void beforeInsert(list<Room__c> roomList) {

        // Create map with Hotels and Rooms list
        Map<Id,List<room__c>> hotelWithRoom=new Map<Id,List<room__c>>();


        // Create list of Hotel Ids
        set<Id> hotelIds = new set<Id>();

            for(room__c room : roomList){
            hotelIds.add(room.Hotel__c);
            }

        // Populate map with Hotel Ids and List of Rooms
        For(Hotel__c hotel :[Select Id,total_rooms__c, (SELECT Room_Number__c from Rooms__r) FROM
                   Hotel__c WHERE Id IN: hotelIds]){

        hotelWithRoom.put(hotel.Id,hotel.rooms__r);
        }

        for(Room__c rc :roomList ){

            for(room__c dupCheck : hotelWithRoom.get(rc.Hotel__c)){

                if(rc.Room_Number__c == dupCheck.Room_Number__c){

                rc.addError('This room number already exisit: ' + rc.Room_Number__c + '. Please choose different number.'); // Prevent Create
                }
                else if (rc.Room_Number__c <=0){

                rc.addError('Room Number cannot be negative: ' + rc.Room_Number__c + '. Please choose different number.'); // Prevent Create

                }

            }

        }
    }



    public static void afterUpdate(list<Room__c> updateRecord ,list<Room__c> oldMapValue) {


        //Create Apex Class to handle Service Rooms List
        //List of all hotels that needs to be updated
        set<Id> underServiceUpdate = new set<Id>();
        set<Id> rentedUpdate = new set<Id>();

        for(room__c r : updateRecord){

            if(r.service__c == true && oldMapValue.get(r.Id).service__c == false){
            underServiceUpdate.add(r.Hotel__c);
            }
            else if(r.occupied__c	== true &&  oldMapValue.get(r.Id).occupied__c == false){



            }

        }





    }
}