force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Rooms_Available__c.field-meta.xml
<CustomField>
    <fullName>Rooms_Available__c</fullName>
    <label>Rooms Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rooms_out_of_service__c.field-meta.xml
<CustomField>
    <fullName>Rooms_out_of_service__c</fullName>
    <label>Rooms out of service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Total_Rented_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Total_Rented_Rooms__c</fullName>
    <label>Total Rented Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/service__c.field-meta.xml
<CustomField>
    <fullName>service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox - if room required service</description>
    <label>service</label>
    <type>Checkbox</type>
</CustomField>

.history/force-app/main/default/classes/HotelDataUpdateQuable_20220228072937.cls
public class HotelDataUpdateQuable {

   // @future
    public static void HotelDataUpdateUnderService(list<Id> recordIds) {

    map<Id,Integer> HotelServiceCT = new map<id,Integer>();
    map<Id,Integer> HotelAvialableCT = new map<id,Integer>();
    map<Id,Integer> HotelRentedleCT = new map<id,Integer>();

    list<Hotel__c> HotelUpdateList = new list<Hotel__c>();


    //Prepare DATA

    AggregateResult[] aggService = [SELECT Hotel__c , count(Id) ct from Room__c WHERE Hotel__c IN: recordIds  AND Service__c = TRUE GROUP BY Hotel__c];

    AggregateResult[] aggAvailable = [SELECT Hotel__c , count(Id) ct from Room__c WHERE Hotel__c IN: recordIds  AND service__c != TRUE AND occupied__c != TRUE  GROUP BY Hotel__c];

    AggregateResult[] aggOccupied = [SELECT Hotel__c , count(Id) ct from Room__c WHERE Hotel__c IN: recordIds  AND occupied__c = TRUE  GROUP BY Hotel__c];


    for(AggregateResult ar : aggService){
        HotelServiceCT.put((Id)ar.get('Hotel__c'),(Integer)ar.get('ct'));
    }
    for(AggregateResult arAvailable : aggAvailable){
        HotelAvialableCT.put((Id)arAvailable.get('Hotel__c'),(Integer)arAvailable.get('ct'));
    }
     for(AggregateResult arOccupied : aggAvailable){
        HotelAvialableCT.put((Id)arAvailable.get('Hotel__c'),(Integer)arAvailable.get('ct'));
    }

    for(Hotel__c h: [SELECT Id,Rooms_out_of_service__c FROM Hotel__c WHERE Id In: recordIds]){
        h.Rooms_out_of_service__c = HotelServiceCT.get(h.Id);
        h.Rooms_Available__c = HotelAvialableCT.get(h.Id);
        h.Total_Rented_Rooms__c = 
        HotelUpdateList.add(h);

    }
    update HotelUpdateList;


    }

  //  @future
    public static void HotelDataUpdateRentedRooms(map<String,Id> recordIds) {
    }
  //   @future
    public static void HotelDataUpdateUnRentedUpdate(map<String,Id> recordIds) {
    }
}