force-app/main/default/objects/Contact/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <inlineHelpText>VIP - 40% discount, access to spa, car discount,premium Wi-Fi
Standard - discount based on num of TTM Reservations.
Internal Employee- 70% discount + VIP</inlineHelpText>
    <label>Customer Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Internal Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Guest_name__c.field-meta.xml
<CustomField>
    <fullName>Guest_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guest Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

.history/force-app/main/default/classes/GuestController_20221128113719.cls
public class GuestController {

    public static List<Contact> discountCalculator(List<Contact> contacts){


        /* Create 
        */
        list<contact> vipContacts = new list<contact>();
        list<contact> standardContacts = new list<contact>();
        list<contact> internalContacts = new list<contact>();

        for(contact c :  [SELECT Id,Customer_Status__c from Contact Where Id IN: contacts]){

                switch on c.Customer_Status__c{
                    when 'VIP' {
                        vipContacts.add(c);
                    }
                    when 'Standard' {
                        system.debug('Andt is sstandard!!');
                        standardContacts.add(c);
                    }
                    when 'Internal Employee' {
                        internalContacts.add(c);
                    }
            }
        }


        IContactDiscount vip = (IContactDiscount) new ContactDiscountVIP();
        calculatedContacts.addAll(vip.calculateDiscount(vipContacts));

        IContactDiscount standard = (IContactDiscount) new ContactDiscountStandard();
        calculatedContacts.addAll(standard.calculateDiscount(standardContacts));

        IContactDiscount internal = (IContactDiscount) new contactDiscountInternal();
        calculatedContacts.addAll(internal.calculateDiscount(internalContacts));


    return calculatedContacts;
}

@AuraEnabled (cacheable = true)
public static list<Contact> guestListfromReservation(list<String> ids){
    return [SELECT Id,LastName from contact where Id IN (SELECT Guest_name__c from Reservation__c WHERE id =: ids)];
}

}