force-app/main/default/objects/Contact/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check-In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_Date__c</fullName>
    <label>Check-out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Guest_name__c.field-meta.xml
<CustomField>
    <fullName>Guest_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guest Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

.history/force-app/main/default/classes/RoomAvailableScheldueTest_20220823033718.cls
@isTest(SeeAllData=true)
public class RoomAvailableScheldueTest {

 // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 24 8 ? 2022';
    @isTest(SeeAllData=true) static void testScheduledJob() {

        Hotel__c h1 = new Hotel__c(Name = 'Test Hotel', City__c = 'Test City');
            insert h1;

        Room__c r1 = new Room__c (Name='Test Room 1',Hotel__c = h1.Id);
            insert r1;

        Contact c1 = new Contact(FirstName = 'Test',LastName='User',Discount__c=0);
            insert c1;

        Reservation__c res = new Reservation__c(
        Name = 'Test reservation',
        Room__c = r1.Id,
        Check_In_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()-2),
        Check_out_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+1),
        Guest_name__c = c1.Id
        );
        insert res;

        Reservation__c res2 = new Reservation__c(
        Name = 'Test reservation',
        Room__c = r1.Id,
        Check_In_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+3),
        Check_out_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+5),
        Guest_name__c = c1.Id
        );
        insert res2;

        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP,
            new RoomAvailableScheldule());
        // Verify the scheduled job has not run yet.
        list<Reservation__c> reservationTestBefore = [Select Id from  Reservation__c WHERE Room__c =: r1.Id];
        system.debug(reservationTestBefore);
        System.assertEquals(2, reservationTestBefore.size(), 'Tasks exist before job has run');

        list<Room__c> reservationTestAfter = [Select Id from  Room__c WHERE Available__c = true AND id =: r1.Id];
        system.debug(reservationTestBefore);
        System.assertEquals(1,reservationTestAfter.size(),'This room is available');

        Test.stopTest();

        // Now that the scheduled job has executed,
        // check that our tasks were created
        list<Room__c> reservationTestAfter = [Select Id from  Room__c WHERE Available__c = true AND id =: r1.Id];
        system.debug(reservationTestBefore);
        System.assertEquals(0,reservationTestAfter.size(),'This room is no longer available');

}
}