force-app/main/default/objects/Contact/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by Cools Kids corporation</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/isApexDefaultReservation__c.field-meta.xml
<CustomField>
    <fullName>isApexDefaultReservation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isApexDefaultReservation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Breakfast__c.field-meta.xml
<CustomField>
    <fullName>Breakfast__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Breakfast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Breakfast_Type__c.field-meta.xml
<CustomField>
    <fullName>Breakfast_Type__c</fullName>
    <label>Breakfast Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Breakfast__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegeterian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Cancelation_fee_covered__c.field-meta.xml
<CustomField>
    <fullName>Cancelation_fee_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelation fee covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check-In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_Date__c</fullName>
    <label>Check-out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Guest_name__c.field-meta.xml
<CustomField>
    <fullName>Guest_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guest Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/Reservation_line_item__c.object-meta.xml
<CustomObject>
    <label>Reservation Line Item</label>
    <nameField>
        <label>Reservation Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation_line_item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>Master Hote record</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

.history/force-app/main/default/classes/ReservationTriggerTest_20220823021653.cls
@isTest(SeeAllData=true)

public class ReservationTriggerTest {

    @isTest(SeeAllData=true) static void testMethod1() {


       PricebookEntry defaultPricebook = [Select Id,Name,Product2Id,UnitPrice from PricebookEntry WHERE Product2.isApexDefaultReservation__c = true];
       Contact guest = [SELECT Id,Name,FirstName,LastName from Contact  LIMIT 1];


       Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Discount__c = 0
       );

       insert testContact;

       Hotel__c testHotel = new Hotel__c(
           Name = 'Test',
           City__c = 'Test city'
       );

       insert testHotel;

       Room__c testRoom = new Room__c(
        Name = 'test Room',
        Hotel__c = testHotel.Id
       );

       insert testRoom;

        Reservation__c rr = new Reservation__c(
            Name = 'Reservation TestSetup',
            Guest_name__c = testContact.Id,
            Room__c = testRoom.Id,
            Check_In_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()),
            Check_out_Date__c = date.newInstance(Date.today().year(), Date.today().month(), date.today().day()),
            Cancelation_fee_covered__c = false
        );


try{
    insert rr;
}

catch(DmlException e)
{
    system.debug(e.getMessage());
}



      List<Reservation__c> newReservations = new list<Reservation__c>();

    for(integer i = 1; i<3;i++){

            Reservation__c r = new Reservation__c(
            Name = 'Reservation ' + i,
            Guest_name__c = guest.Id,
            Room__c = testRoom.Id,
            Check_In_Date__c =  i > 1 ? date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+2 : date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+2),
            Check_out_Date__c = i > 1 ? date.newInstance(2022, 6, 21) : date.newInstance(Date.today().year(), Date.today().month(), date.today().day()+4)
        );

        newReservations.add(r);
    }

        try {
           // Database.Insert(newReservations, false);
           Insert newReservations;
        }
        catch(DmlException e){

            system.debug(e.getMessage());
            Boolean expectedExceptionThrown =  e.getMessage().contains('Please choose different room or different date.') ? true : false;
            system.assertEquals(expectedExceptionThrown, true);
        }

        list<Reservation__c> testReservations = [Select Id,Name,Check_In_Date__c,Check_out_Date__c,Room__c From Reservation__c WHERE Room__c =: testRoom.Id];

      //  System.assertEquals(2, testReservations.size());


        Reservation__c r1 = new Reservation__c(
            Name = 'Reservation  test f',
            Guest_name__c = guest.Id,
            Room__c = testRoom.Id,
            Check_In_Date__c =  date.newInstance(2022, 7, 10),
            Check_out_Date__c = date.newInstance(2022, 7, 11)
        );

        try {
           // Database.Insert(newReservations, false);
           Insert r1;
           system.debug('inserted record = ' + r1 );
        }
        catch(DmlException f){

            system.debug(f.getMessage());
}

    list<Reservation__c> rtest = [select id,Name,Check_In_Date__c,Check_out_Date__c from Reservation__c WHERE Room__c =: testRoom.Id];
    room__c roomTest = [SELECT id,Available__c,occupied__c from Room__c WHERE id =: testRoom.Id];

    system.debug(rtest);
    system.assertEquals(2,rtest.size());
    system.assertEquals(roomTest.occupied__c,true);


        // test delete reservation

    Reservation__c delReservation = [SELECT Id,Name from Reservation__c WHERE Name = 'Reservation TestSetup'];

     try {
           delete delReservation;
        }
        catch(DmlException d1){

            system.debug(d1.getMessage());
            Boolean expectedExceptionThrown =  d1.getMessage().contains('You can not cancel this reservation') ? true : false;
            system.assertEquals(expectedExceptionThrown, true);
        }


    Reservation__c r1delete = new Reservation__c(
            Name = 'Reservation  test f',
            Guest_name__c = guest.Id,
            Room__c = testRoom.Id,
            Check_In_Date__c =  date.newInstance(2022, 7, 22),
            Check_out_Date__c = date.newInstance(2022, 7, 27),
            Cancelation_fee_covered__c = false,
            Breakfast__c = true,
            Breakfast_Type__c = 'Vegetarian'
        );

        try{
            insert r1delete;
        }
        catch(DmlException d3){

            system.debug(d3.getMessage());
        }


        List<Reservation_line_item__c> testBreakfast = [SELECT id,Name from Reservation_line_item__c WHERE Reservation__c =:r1delete.Id];
        system.assertEquals(2, testBreakfast.size());


     try {

           delete r1delete;
        }
        catch(DmlException d2){

            system.debug(d2.getMessage());
            Boolean expectedExceptionThrown =  d2.getMessage().contains('You can not cancel this reservation') ? true : false;
            system.assertEquals(expectedExceptionThrown, false);
        }


}
}