force-app/main/default/objects/Contact/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Room Rservations</description>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Breakfast__c.field-meta.xml
<CustomField>
    <fullName>Breakfast__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Breakfast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Breakfast_Type__c.field-meta.xml
<CustomField>
    <fullName>Breakfast_Type__c</fullName>
    <label>Breakfast Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Breakfast__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegeterian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Cancelation_fee_covered__c.field-meta.xml
<CustomField>
    <fullName>Cancelation_fee_covered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelation fee covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Cancelation_without_cost__c.field-meta.xml
<CustomField>
    <fullName>Cancelation_without_cost__c</fullName>
    <description>You can cancel with no cost only 3&lt; before check in</description>
    <formula>Check_In_Date__c - today() &gt; 3</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cancelation without cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check-In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_Date__c</fullName>
    <label>Check-out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Days_number__c.field-meta.xml
<CustomField>
    <fullName>Days_number__c</fullName>
    <formula>Check_out_Date__c -  Check_In_Date__c</formula>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Guest_name__c.field-meta.xml
<CustomField>
    <fullName>Guest_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guest Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/Reservation_line_item__c.object-meta.xml
<CustomObject>
    <label>Reservation Line Item</label>
    <nameField>
        <label>Reservation Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation_line_item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Reservation Line Items</relationshipLabel>
    <relationshipName>Reservation_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation_line_item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Quantity * Pricebook Entry</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room ready to book</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/occupied__c.field-meta.xml
<CustomField>
    <fullName>occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is room available at the moment</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

.history/force-app/main/default/classes/ReservationTriggerHandler_20220309101229.cls
public class ReservationTriggerHandler {

     public static void updateContactDiscount(List<Reservation__c> reservations){

        list<Reservation__c> resList = [Select Id,Guest_name__r.Id from Reservation__c WHERE Id IN: reservations];

        List<Contact> contacts = new list <Contact>();

        for(Reservation__c r : resList){

            contacts.add(r.Guest_name__r);
        }

        List<Contact> contactsToUpdate = GuestController.discountCalculator(contacts);

        update contactsToUpdate;

    }


    public static void beforeDeleteReservation(List<Reservation__c> reservations){

        for(Reservation__c r : reservations){

            if(r.Cancelation_without_cost__c == false && r.Cancelation_fee_covered__c  == false){

            r.addError('You can not cancel this reservation without paying cancelation fee.');

            }

        }

    }

    // Create task to update Room Information

    public static void afterInsertUpdateRoomAvailability(List<Reservation__c> reservations){

    // Store all rooms from New reservations list
        set<Id> roomList = new set<Id>();
        list<Room__c> updateListRoom = new list<Room__c>();

        for(Reservation__c rl :reservations){

            if(rl.Check_In_Date__c <= date.today() && rl.Check_out_Date__c >= date.today()){
                roomList.add(rl.Room__c);
            }
        }

        for(Room__c r: [Select Id,Name from Room__c WHERE Id IN: roomList]){

            r.Available__c = false;
            r.occupied__c = true;

            updateListRoom.add(r);
        }
        update updateListRoom;

    }

    // Create Default Reservation Item for new Reservation

    public static void createReservationItem(List<Reservation__c> reservations){

        List<Reservation_line_item__c> newReservations = new list<Reservation_line_item__c>();

        PricebookEntry defaultPricebook = [Select Id,Name,Product2Id,UnitPrice from PricebookEntry WHERE Product2Id = '01t7Q000000VIqvQAG'];


        list<Reservation__c> reservationQuery= [SELECT Id,Name,Guest_name__r.Name,Guest_name__r.Discount__c FROM Reservation__c WHERE Id IN: reservations];

        map<Id,Reservation__c> reservationMap = new map<Id,Reservation__c>(reservationQuery);

        for(Reservation__c r: reservations){

            Reservation_line_item__c rlineItem = new Reservation_line_item__c(
                Name = r.Name + ' - ' + r.Days_number__c + ' stay. ' + reservationMap.get(r.Id).Guest_name__r.Name,
                Product__c = defaultPricebook.Product2Id,
                Reservation__c = r.Id,
                Quantity__c = r.Days_number__c,
                Discount__c = reservationMap.get(r.Id).Guest_name__r.Discount__c,
                List_Price__c =  defaultPricebook.UnitPrice * r.Days_number__c,
                Total_Price__c = (defaultPricebook.UnitPrice * r.Days_number__c) * (1 - (reservationMap.get(r.Id).Guest_name__r.Discount__c/100))
            );
            newReservations.add(rlineItem);

            if(r.Breakfast__c == true){

                switch on r.Breakfast_Type__c{


                    WHEN 'English Breakfast'{

                    }
                    
                    WHEN 'English Breakfast'{
                        
                    }

                }

            }

        }

        insert newReservations;

    }


    public static void checkIfRoomAvailable(List<Reservation__c> reservations){


    // Store all rooms from New reservations list
        List<Id> roomList = new list<Id>();

        for(Reservation__c rl :reservations){
        roomList.add(rl.Room__c);
        }


        map<Id,list<Reservation__c>> roomReservations = new map<Id,list<Reservation__c>>();

        list<Room__c> roomWithReservations = [SELECT Id, Name, (SELECT Id, Name, Check_In_Date__c, Check_out_Date__c, Room__c FROM Reservations__r) FROM Room__c WHERE Id IN : roomList];

        for(Room__c r : roomWithReservations ){

        roomReservations.put(r.Id,r.Reservations__r);

        }

        set<Reservation__c> resInvalid = new set<Reservation__c>();
        set<Reservation__c> dupes = new set<Reservation__c>();

        for(Reservation__c res : reservations){

            for(Reservation__c checkDupe : roomReservations.get(res.Room__c)){


                if(
                    (res.Check_In_Date__c > checkDupe.Check_In_Date__c && res.Check_In_Date__c < checkDupe.Check_out_Date__c) ||
                    (res.Check_out_Date__c > checkDupe.Check_In_Date__c && res.Check_out_Date__c < checkDupe.Check_out_Date__c) ||
                    (res.Check_In_Date__c == checkDupe.Check_In_Date__c && res.Check_In_Date__c == checkDupe.Check_out_Date__c)
                    ){
                        resInvalid.add(res);
                    }

            }

            set<Reservation__c> rset = new set<Reservation__c>(resInvalid);

            if(resInvalid.size() > 0 && resInvalid.contains(res)){

                res.addError('This Room is already booked at this time. '  + ' Please choose different room or different date.'); // Prevent Create

            }

        }

        }

}